services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - database
        networks:
            - symfony


    ###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        container_name: symfony_db
        environment:
            POSTGRES_DB: app
            # You should definitely change the password in production
            POSTGRES_PASSWORD: myverysecretpassword
            POSTGRES_USER: app
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - symfony

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - symfony
###< doctrine/doctrine-bundle ###

networks:
    symfony:
        driver: bridge
